server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          uri: https://github.com/southwind9801/orderingsystem.git #git仓库地址
          searchPaths: config #仓库路径
          username: 651370356@qq.com #git仓库用户名
          password: teto0609... #git仓库密码
      label: master #仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/